export const BOOK_CATEGORIES = [
  "Fiction",
  "Fantaisie",
  "Science-Fiction",
  "Policier",
  "Thriller",
  "Romance",
  "Historique",
  "Biographie",
  "Développement Personnel",
  "Essai",
  "Non-fiction",
  "Jeunesse",
  "Bande Dessinée",
  "Manga",
  "Classique",
  "Poésie",
  "Théâtre",
  "Autre",
];
